import ruteSmgCilacap
from ordereddict import OrderedDict

company_name = 'PO. Sumber Alam'
bus_plateno = 'Raspi-LCD40x4-1'
bus_id = 27

# gps and gprs port now configured in configusb.py, which is automatically generated by first2.py
printer_port='/dev/ttyAMA0'
printer_enabled = True
gprs_baudrate=9600
gps_baudrate=9600
gpsgprs_gpio_ip='localhost'
#~ gpsgprs_gpio_ip='192.168.1.105'
gpsgprs_pubport=5600
gpio_pubport=5601
gpsgprs_pullport=5602
gpio_repport=5603
server_ip= '175.41.145.80'
server_port = 8045

route = ruteSmgCilacap.route

price_per_km = 280
minimal_price = 2000

agents = OrderedDict([
	("T. Terboyo",	{'latlon': (110.462975744158, -6.95384580641985),	'radius': 1000}), 
	("Kantor IT PRO",	{'latlon': (110.426625, -6.993487),	'radius': 1000}), 
	("Sukun",				{'latlon': (110.413206936792, -7.06509461626411),	'radius': 1000}), 
	("Garasi Pudakpayung",	{'latlon': (110.4099235777,-7.0989063755),			'radius': 1000}),	
	("T. Bawen",		{'latlon': (110.4337694217, -7.245006552),			'radius': 1000}), 
	("Tanjung / Magelang",	{'latlon': (110.187828456983, -7.52463195472956),	'radius': 1000}),
	("Kaliboto",			{'latlon': (110.049211895093, -7.65045982785523),	'radius': 1000}), 
	("Brengkelan",			{'latlon': (110.01927902922, -7.70454799756408), 	'radius': 1000}), 
	("T. Purworejo",	{'latlon': (109.967464953661, -7.72800751961768),	'radius': 1000}), 
	("Kutoarjo",			{'latlon': (109.9062432814, -7.722858265), 		'radius': 1000}), 
	("RM Ngandong",			{'latlon': (109.881962416694, -7.72480747662485),	'radius': 1000}), 
	("Leo Prembun",			{'latlon': (109.802533071488, -7.72449005395174),	'radius': 1000}), 
	("Kutowinangun",		{'latlon': (109.736100118607, -7.72165780887008),	'radius': 1000}), 
	("T. Kebumen",	{'latlon': (109.678658265621, -7.69742991775275),	'radius': 1000}), 
	("Karanganyar",			{'latlon': (109.588919011876, -7.65229370445013),	'radius': 1000}), 
	("Gombong",				{'latlon': (109.507830636576, -7.60913721285761),	'radius': 1000}), 
	("Tambak",				{'latlon': (109.397742636502, -7.61323562823236),	'radius': 1000}), 
	("Sumpiuh",				{'latlon': (109.365777, -7.613277),	'radius': 1000}), 
	("Buntu",				{'latlon': (109.272388, -7.592694),	'radius': 1000}), 
	("Sampang",				{'latlon': (109.200222, -7.562555),	'radius': 1000}), 
	("Maos",				{'latlon': (109.13994429633, -7.62021213769913), 	'radius': 1000}), 	
	("Cilacap",				{'latlon': (109.0249472670, -7.7022626717), 		'radius': 1000}), 	
])

group1pergi = ["Terminal Terboyo", "Kantor IT PRO","Sukun", "Garasi Pudakpayung", "Terminal Bawen", "Tanjung / Magelang", "Kaliboto", "Brengkelan", "Terminal Purworejo"]
#group1pergi = ["T. Terboyo", "Sukun", "Garasi Pudakpayung", "T. Bawen", "Tanjung / Magelang", "Kaliboto", "Brengkelan", "T. Purworejo"]
group2pergi = ["Kutoarjo", "RM Ngandong", "Leo Prembun", "Kutowinangun", "T. Kebumen", "Karanganyar", "Gombong", "Tambak", "Sumpiuh", "Buntu", "Sampang", "Maos", "Cilacap"]
groupallpergi = group1pergi + group2pergi

group1pulang = ["T. Terboyo", "Kantor IT PRO", "Sukun", "Garasi Pudakpayung", "T. Bawen", "Tanjung / Magelang", "Kaliboto", "Brengkelan", "T. Purworejo", "Kutoarjo"]
#group1pulang = ["T. Terboyo", "Sukun", "Garasi Pudakpayung", "T. Bawen", "Tanjung / Magelang", "Kaliboto", "Brengkelan", "T. Purworejo", "Kutoarjo"]
group2pulang = ["RM Ngandong", "Leo Prembun", "Kutowinangun", "T. Kebumen", "Karanganyar", "Gombong", "Tambak", "Sumpiuh", "Buntu", "Sampang", "Maos", "Cilacap"]
groupallpulang= group1pulang + group2pulang

destinations = [
	# PERGI
	OrderedDict([
		('Semarang',	{
			'latlon': (110.462975744158, -6.95384580641985), 	
			'pricelist': [
				{'from': groupallpergi,	'price': 41000},
			]
		}), 
		('Magelang',	{
			'latlon': (110.187828456983, -7.52463195472956),
			'pricelist': [
				{'from': groupallpergi,	'price': 41000},
			]
		}), 
		('Purworejo',	{
			'latlon': (109.967464953661, -7.72800751961768),
			'pricelist': [
				{'from': groupallpergi,	'price': 41000},
			]
		}), 
		('Gombong',		{
			'latlon': (109.507830636576, -7.60913721285761), 	
			'pricelist': [
				{'from': group1pergi,	'price': 80000},
				{'from': group2pergi,	'price': 41000},
			]
		}),  
		('Cilacap',		{
			'latlon': (109.0249472670, -7.7022626717),
			'pricelist': [
				{'from': group1pergi,	'price': 80000},
				{'from': group2pergi,	'price': 41000},
			]
		}), 	
	]),
	# PULANG
	OrderedDict([
		('Cilacap',		{
			'latlon': (109.0249472670, -7.7022626717),	
			'pricelist': [
				{'from': groupallpulang,	'price': 41000},
			]
		}), 	
		('Gombong',		{
			'latlon': (109.507830636576, -7.60913721285761), 
			'pricelist': [
				{'from': groupallpulang,	'price': 41000},
			]
		}),  
		('Purworejo',	{
			'latlon': (109.967464953661, -7.72800751961768), 	
			'pricelist': [
				{'from': groupallpulang,	'price': 41000},
			]
		}),
		('Magelang',	{
			'latlon': (110.187828456983, -7.52463195472956), 
			'pricelist': [
				{'from': group1pulang,	'price': 41000},
				{'from': group2pulang,	'price': 80000},
			]
		}), 		
		('Semarang',	{
			'latlon': (110.462975744158, -6.95384580641985), 
			'pricelist': [
				{'from': group1pulang,	'price': 41000},
				{'from': group2pulang,	'price': 80000},
			]
		}), 
	])
]



